### ISSUE TITLE
How can I add integer to the player account file

### ISSUE THREAD

**Issue by ST-Chara** [EMokro/uhcity#2]
I made a multi-Language system, and i want save player language in Account file.

**Comment by UrinStone** [comment]
Checkout the account.cpp. You can simply add the Field, just as the others. Make sure to check the fields value for undefined or Null.

**Comment by ST-Chara** [comment]
But will it make the old account data unreadable?

**Comment by ST-Chara** [comment]
My server has more than 300 registered accounts

**Comment by UrinStone** [comment]
No, newly added account data will not destroy old account files. The JSON files gets parsed and you need to handle the undefined properties.
The account files get overridden completely each time it's updated.
